### ISSUE TITLE
Request: light mode

### ISSUE THREAD

**Issue by trombonehero** [shuber2/mutt-gruvbox#4]
Thanks very much for this theme... it really integrates Mutt into my setup nicely!

Would you consider creating a `-light` variant of these themes? During the daytime, I tend to use Gruvbox Light for my terminal, vim, etc., and it would be great if I could do the same with Mutt.

**Comment by shuber2** [comment]
I am sorry, it Is not planned. If you would consider providing one, I would be happy to add it to the repo.
